name: Build PyQt6 App for Windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyqt6 pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyQt6-App
          path: dist/main.exe
