name: Build & Release PyQt6 App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # ✅ cần để tạo release
  packages: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyqt6 pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyQt6-App
          path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: PyQt6-App
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
